In [ ]:
# numpy = ndArray 다차원

import numpy as np

# 다차원 배열의 생성 역할
# 1차원 nbArray 생성

np.array([1, 2, 3, 4])

arr1 = np.array([1, 2, 3, 4])  # 넘파이 ncArray
arr2 = [1, 2, 3, 4]

print(arr1)
print(arr2)

print(type(arr1)) # 넘파이로 이루어진 다차원 배열
print(type(arr2)) # 그냥 리스트 형태태

[1 2 3 4]
[1, 2, 3, 4]
<class 'numpy.ndarray'>
<class 'list'>


In [5]:
# 2차원 anArray 생성
# 1차원 배열 두개가 리스트로 묶인 형태가 2차원 배열이다

arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr2)


# 3차원 anArray 생성

arr3 = np.array([[[1,2,3,4], [1,2,3,4]], [[1,2,3,4], [1,2,3,4]]])

print(arr3)



[[1 2 3 4]
 [5 6 7 8]]
[[[1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]]]
