In [1]:
# numpy = ndArray 다차원

import numpy as np

# 다차원 배열의 생성 역할
# 1차원 nbArray 생성

np.array([1, 2, 3, 4])

arr1 = np.array([1, 2, 3, 4])  # 넘파이 ncArray
arr2 = [1, 2, 3, 4]

print(arr1)
print(arr2)

print(type(arr1)) # 넘파이로 이루어진 다차원 배열
print(type(arr2)) # 그냥 리스트 형태태

[1 2 3 4]
[1, 2, 3, 4]
<class 'numpy.ndarray'>
<class 'list'>


In [4]:
# 2차원 anArray 생성
# 1차원 배열 두개가 리스트로 묶인 형태가 2차원 배열이다

arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr2)


# 3차원 anArray 생성

arr3 = np.array([[[1,2,3,4], [1,2,3,4]], [[1,2,3,4], [1,2,3,4]]])

print(arr3)



[[1 2 3 4]
 [5 6 7 8]]
[[[1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]]]


In [10]:
# ndim : 몇 차원 배열인지를 알려줌려줌
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

# shape : 배열의 형태를 알려줌줌
print(arr1.shape)  # 4개의 열
print(arr2.shape)  # 행 2개, 열 4개
print(arr3.shape)  # 2 * 2 * 4

# size : 요쇼의 개수
print(arr1.size)
print(arr2.size)
print(arr3.size)

# dtype : 요소의 타입
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

1
2
3
(4,)
(2, 4)
(2, 2, 4)
4
8
16
int64
int64
int64


In [15]:
# zeros : 요소를 0으로 채운 행렬

arr4 = np.zeros((3, 4))
print(arr4)

# ones : 요소를 1로 채운 행렬렬

arr5 = np.ones((2, 3, 4))
print(arr5)

# full : i 값으로 채워진 행렬(임의의 숫자)

arr6 = np.full((4, 4), 3)
print(arr6)

# like : 다른 배열의 모양을 본따 만듦

print(np.zeros_like(arr5))
print(np.ones_like(arr5))
print(np.full_like(arr5, 2))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]

 [[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]]


In [ ]:
# random : 난수를 발생시킴

arr7 = np.random.randint(-100, 100, (2, 3))
np.random.seed(1)  # 난수를 발생시킨 시점 저장
np.random.seed(2)  

np.random.randint(0, 10, (2, 2, 3))
print(arr7)

[[-63  40 -28]
 [ 37  33 -21]]


In [40]:
# indexing 
#li = [1, 2, 3, 4]
#li[0]

# 1차원 배열의 인덱싱
#arr1[0] # 한개 접근

# 1차원 슬라이싱
# arr1[시작:끝:보폭]
# arr1[1:5:1]  // 1에서 5까지 1씩

#arr[1:2:]

# 2차원 배열의 인덱싱
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr2[0, 1])
print(arr2[1, 2])
print(arr2[1:2:, 1:3:])

# fancy 인덱싱 : 원하는 익덱스를 배열로 넘겨주는 인덱싱
# 1차원
arr1[[0, 1, 3]]
print(arr1)
# 2차원
arr2[[0,1], [1,3]]
print(arr2)
arr2[::, [0,3]]


# 논리값 인덱싱
arr1[[True, False, True, False]]
arr1[arr1>2]


2
7
[[6 7]]
[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]


array([3, 4])